spring:
  application:
    name: ame=OAuth2
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 607507858836-j37f47bicsr18nn4hdvb3j85v5tdj688.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


server:
   port: 9090

security:
  oauth2:
    client:
      clientId: 607507858836-j37f47bicsr18nn4hdvb3j85v5tdj688.apps.googleusercontent.com
      client-secret: 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
      accessTokenUri: https://oauth2.googleapis.com/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
              - email
              - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo



#security:
#   oauth2:
#     client:
#        clientId: 1031477951727359
#        clientsecretId: 4f9b5466d9dee8782e6eba59f9929bca
#        accessTokenUri: https://graph.facebook.com/oauth/access_token
#        userAuthorizationUri: https://www.facebook.com/dialog/oauth
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthenticationScheme: form
#     resource:
#        userInfoUri: https://graph.facebook.com/me
        
        
#607507858836-j37f47bicsr18nn4hdvb3j85v5tdj688.apps.googleusercontent.com
#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